shadow/config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :publishers
  devise_for :writers
    
    resources :articles do
  resources :comments
    end
  

    root 'articles#index'

end

shadow/app/models/article.rb
class Article < ActiveRecord::Base
     has_many :comments
    
    validates_presence_of :title
    validates_presence_of :body
    belongs_to :writer
    
    validates_presence_of :title
    validates_length_of :title, :in => 5..30, :message => "longitud invalida"
    validates_presence_of :body
    validates :body, length: { maximum: 500, message: "El texto del post es muy largo"}
    validates :body, length: { minimum: 10, message: "el texto del post es corto"}
    
     has_attached_file :image
    
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
    
    has_attached_file :csvdata,
    :url => "/controllers/articles/:basename.:extension"
    
    
end

shadow/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
      
      if publisher_signed_in?
          
     @articles = Article.all
          
      elsif writer_signed_in?
          
          @articles = current_writer.articles
#   
#        
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
      
#    @article = Article.new(article_params)
      
      @article = Article.new(article_params)
      @article.writer_id = current_writer.id

    respond_to do |format|
      if @article.save
          flash[:success] = "The article was successfully savede"
         format.html {redirect_to @article}
         format.json { render :show, status: :created, location: @article }
      else
        flash[:alert] = "There was a problem saving Article"  
        format.html { render :new }
         format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
        params.require(:article).permit(:title, :body, :image)
    end
end

shadow/app/helpers/articles_helper.rb
module ArticlesHelper
end

shadow/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <div class="large-10">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
</div>

<!--#esto estaba sin section-->
<div class="field">
    <div class="large-10">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
</div>
    
  <div class="field">
    <div class="large-10">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
</div>

  <div class="actions">
    <%= f.submit'ACEPTAR', :class => 'button small'%>
  </div>
<% end %>

shadow/app/views/articles/_navigation.html.erb
<div class="top-b">
  <div class="top-bar-left">
    <ul class="menu" data-dropdown-menu>
      <li class="menu-text">Practica rails</li>
      <li>
        
      </li>
        <li><%= link_to "home", controller: "/articles", action: "index" %></li>
        <li><% if writer_signed_in? %>
            
            <%= link_to "nuevo Article", controller: "/articles", action: "new" %>
              <% else %>
            
           
          
          <%end%>
          
          
          </li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
        <% if writer_signed_in? %>
        <li> <strong><%= current_writer.email %></strong> </li>
        
        <li><%= link_to 'Edit profile', edit_writer_registration_path, :class => 'navbar-link' %></li>
       <li> <%= link_to "Logout", destroy_writer_session_path, method: :delete, :class => 'navbar-link' %> </li>
       
        
        
        <% elsif publisher_signed_in? %>
        <li> <strong><%= current_publisher.email %></strong> </li>
        <li><%= link_to 'Edit profile', edit_publisher_registration_path, :class => 'navbar-link' %></li>
        <li> <%= link_to "Logout", destroy_publisher_session_path, method: :delete, :class => 'navbar-link' %> </li>
          <% else %> 
        <li> <%= link_to "Sign up", new_writer_registration_path, :class => 'navbar-link' %> </li>
        <li> <%= link_to "Login", new_writer_session_path, :class => 'navbar-link' %> </li>
        <li> <%= link_to "Login publisher", new_publisher_session_path, :class => 'navbar-link' %> </li>
        <% end %>
        
    </ul>
  </div>
</div>


shadow/app/views/articles/edit.html.erb
<h1>Editar articulo</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

shadow/app/views/articles/index.html.erb
<h1 class="LA">"Articulos"</h1>

<table class="TB">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Imagen</th>
      <th>Cuerpo</th>
        <% if publisher_signed_in? %> 
        <th>Escritor</th> <% else %>  <% end %> 
        
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<section class="tablas">
          <div class="small-4 columns">
      
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
          
         <td><%= image_tag article.image.url(:original) %></td>
          
          
          <td>
              <% if article.body.length > 0 %>
              <a href="#" data-open="article-<%= article.id %>">Descripcion </a>
              <div id="article-<%= article.id%>" class="reveal" data-reveal>
                  
                  <%= article.body %>
                <button class="close-button" data-close aria-label="cerrar" type="button">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
              
              <% end %>
          </td>
          
          <% if publisher_signed_in? %>
          <td>
              <%= Writer.find(article.writer_id).email %></td>
          <% else %>
          
          <% end %>
          
          
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
          
        <td>
            <% if writer_signed_in? %>
             
              <% else %>
            
            <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          
          <% end %>
          
          
      </tr>
                <% end %>
    </div>
  
      </section>
    
  </tbody>
</table>

<br>
<% if writer_signed_in? %>
<%= link_to 'New Article', new_article_path %>
<% else %>
<% end %>

shadow/app/views/articles/new.html.erb
<h1 class="NA">Nueva entrada</h1>
<section class="O">

<%= render 'form' %>

<%= link_to 'Back', articles_path %>
</section>

shadow/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<%= image_tag @article.image.url(:medium) %>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>